export default {
    createProduct : "/api/financial/paystack/transaction/product/",
    bank : "/api/financial/paystack/misc/bank",
    subaccount : "/api/financial/paystack/subaccount",
    transaction : "/api/financial/paystack/transaction/secure",
    verifyTransact : "/api/financial/paystack/transaction/verify",
    backpack : "/api/storage/backpack",
    bacpackIdentity: "/api/storage/backpack/identity",
    genusIdentity: "/api/storage/genus/identity",
    plug : "/api/storage/theplug",
    plugProduct : "/api/storage/theplug/identity",
    guap : "/api/storage/guap",
    getGuap : "/api/storage/guap/identity",
    order : "/api/storage/order",
    issue : "/api/resource/github/issue",
    comment : "/api/resource/github/comment",
    createToken : "/api/token",
    readToken : "/api/token/read",
}